#!/usr/bin/php
<?php
/**
 * Hook to tell you, when you have to trigger composer install
 * Installation:
 * cd .git/hooks/
 * ln -s ../../git-hooks/post-merge .
 */

$rootPath = dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR;
$lockFile = $rootPath.'composer.lock';
$hashFile = $rootPath.'app'.DIRECTORY_SEPARATOR.'runtime'.DIRECTORY_SEPARATOR.'composer-lock-hash';

function msg() {
    echo "\n================\n";
    echo "Important Notice\n";
    echo "================\n\n";
    echo "Your composer.lock file has been updated, please run \n\n  php composer.phar install\n\nto ensure vendor folder integrity!\n";
    echo "\n";
}

$currentHash = md5_file($lockFile);
if (is_file($hashFile)) {
    $lastHash = file_get_contents($hashFile);
    echo "\nVerifying composer Installation";
    echo "\nLast Install Hash   : ".$lastHash;
    echo "\nCurrent Install Hash: ".$currentHash;
    if ($lastHash != $currentHash) {
        msg();
    }
} else {
    msg();
}

echo "\n";

file_put_contents($hashFile,$currentHash);

exit(0);
