<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => 'Über uns',
  'Append Child Page' => '',
  'Append Sibling Page' => '',
  'Application' => 'Anwendung',
  'Body' => 'Nachricht',
  'Browse' => 'Verwalten',
  'Choose Language' => 'Sprache wechseln',
  'Contact Us' => 'Kontakt',
  'Email' => 'E-Mail',
  'Error' => 'Fehler',
  'Fields with' => 'Felder mit',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Sollten Sie geschäftliche oder sonstige Frage haben, verwenden Sie bitte das folgende Formular. Vielen Dank.',
  'List' => 'Liste',
  'Login' => 'Anmelden',
  'Logout' => 'Abmelden',
  'Manage' => 'Verwalten',
  'Media' => 'Medien',
  'Name' => '',
  'Overview' => 'Übersicht',
  'Pages' => 'Seiten',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Bitte geben Sie die nebenstehenden Buchstaben ein.<br/>Groß- und Kleinschreibung ist nicht zu beachten.',
  'Profile' => 'Profil',
  'Rights' => 'Rechte',
  'Settings' => 'Einstellungen',
  'Sitemap' => '',
  'Subject' => 'Betreff',
  'Submit' => 'Senden',
  'Template' => '',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Vielen Dank für Ihre Kontaktaufnahme. Wir werden Ihnen schnellstmöglich antworten.',
  'This is a "static" page. You may change the content of this page by updating the file' => 'Dies ist eine "statische" Seite. Um den Inhalt anzupassen, verändern Sie die Datei',
  'Translation' => 'Übersetzung',
  'Upload' => 'Hochladen',
  'User' => 'Benutzer',
  'Users' => 'Benutzer',
  'Verification Code' => 'Verifizierungscode',
  'Widgets' => '',
  'are required' => 'sind erforderlich',
);
