FROM phundament/app:production

# Prepare composer
# /!\ Note: Please add your own API token to config.json; Phundament comes with a public token for your convenince, which may hit a rate limit
ADD ./build/composer/config.json /root/.composer/config.json

# Install packages first (non-development only)
ADD ./composer.lock /app/composer.lock
ADD ./composer.json /app/composer.json
RUN /usr/local/bin/composer install --prefer-dist --no-dev --optimize-autoloader

# Add application code
ADD . /app

# Staging
# -------
# Uncomment to enable password protection (demo/demo) for app server
#ADD docs/examples/docker-staging/default     /etc/nginx/sites-available/default
#ADD docs/examples/docker-staging/.htpasswd   /etc/nginx/.htpasswd
