<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accounts' => '',
  'Append Child' => '',
  'Append Sibling' => '',
  'Assignments' => '',
  'Browser' => '',
  'Create Translation' => '',
  'Dashboard' => '',
  'Dictionaries' => '',
  'Home' => '',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => '',
  'Local File Scan' => '',
  'Permissions' => '',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => '',
  'Registry' => '',
  'Roles' => '',
  'Sitemap' => '',
  'Subject' => '',
  'Submit' => '',
  'Thank you for contacting us. We will respond to you as soon as possible.' => '',
  'This is a "static" page. You may change the content of this page by updating the file' => '',
  'Translate Missing' => '',
  'Translations' => '',
  'Update' => '',
  'Update Translation' => '',
  'User List' => '',
  'Verification Code' => '',
  'Widgets' => '',
  'Append Child Page' => '@@Pievienot apakšlapu@@',
  'Append Sibling Page' => '@@Pievienot māsas lapu @@',
  'Choose Language' => '@@Izvēlaties valodu@@',
  'Manage' => '@@Uzturēt@@',
  'Settings' => '@@Uzstādijumi@@',
  'Translation' => '@@Tulkošana@@',
  'About' => 'Par',
  'Application' => 'Aplikācija',
  'Body' => 'Teksts',
  'Browse' => 'Pārlūkot',
  'Contact Us' => 'Kontakti',
  'Email' => 'Epasts',
  'Error' => 'Kļūda',
  'Fields with' => 'Ievadlauki ar',
  'List' => 'Saraksts',
  'Login' => 'Autorizeties',
  'Logout' => 'Iziet',
  'Media' => 'Mēdijs',
  'Name' => 'Nosaukums',
  'Overview' => 'Apskats',
  'Pages' => 'Lapa',
  'Profile' => 'Profils',
  'Rights' => 'Pieejas tiesības',
  'Upload' => 'Augšuplādēt',
  'User' => 'Lietotājs',
  'Users' => 'Lietotāji',
  'are required' => 'obligāts',
);
