<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-03-03 22:09:45
 */
return [
    'frontend' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@app/web/assets-prod',
        'baseUrl' => '@web/assets-prod',
        'js' => [
            'js/frontend-388d84f6ed8275dbc7badc62080ffb2c.js',
        ],
        'css' => [
            'css/frontend-a667bae5eb9ecb83d8ac5e96773f3432.css',
        ],
    ],
    'backend' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@app/web/assets-prod',
        'baseUrl' => '@web/assets-prod',
        'js' => [
            'js/backend-d52e57bafdef6a94f6d1c7243bc90b8b.js',
        ],
        'css' => [
            'css/backend-e4cd599baba97b296c477cb4eee10bcd.css',
        ],
    ],
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@app/web/assets-prod',
        'baseUrl' => '@web/assets-prod',
        'js' => [
            'js/all-568edf58c6ef2ebd11b55b8dc63b5ce4.js',
        ],
        'css' => [
            'css/all-bb8b94f9263491f08c5897853be9d15b.css',
        ],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'frontend',
        ],
    ],
    'dmstr\\web\\AdminLteAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'rmrevin\\yii\\fontawesome\\AssetBundle',
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'backend',
        ],
    ],
    'app\\modules\\admin\\assets\\AdminAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'dmstr\\web\\AdminLteAsset',
            'backend',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'rmrevin\\yii\\fontawesome\\AssetBundle' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'all',
        ],
    ],
];