# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 8000, host: 8280
    web.vm.provider "docker" do |docker|
      docker.vagrant_vagrantfile = ENV["DOCKER_HOST_VAGRANTFILE"]
      docker.build_dir = "."
      docker.cmd = ["php","-S","0.0.0.0:8000","-t","/app/frontend/web"]
      docker.env = {
          "YII_DEBUG" => true,
          "YII_ENV" => "dev",
          "APP_NAME" => "Phundament 4 Docker & Vagrant",
          "APP_ADMIN_EMAIL" => "admin@myapp.local",
          "APP_ADMIN_PASSWORD" => "admin1234",
          "APP_SUPPORT_EMAIL" => "support@myapp.local",
          "DATABASE_DSN" => "mysql:host=172.17.42.1;dbname=p4",
          "DATABASE_USER" => "dev",
          "DATABASE_PASSWORD" => "dev-123"
        }
    end
  end

  config.vm.define "db" do |db|
    db.vm.network "forwarded_port", guest: 3306, host: 3306
    db.vm.provider "docker" do |docker|
      docker.vagrant_vagrantfile = ENV["DOCKER_HOST_VAGRANTFILE"]
      docker.image = "mysql"
      docker.env = {
        "MYSQL_ROOT_PASSWORD" => "secretroot",
        "MYSQL_USER" => "dev",
        "MYSQL_PASSWORD" => "dev-123",
        "MYSQL_DATABASE" => "p4"
      }
    end
  end

end
